In [1]:
# import numpy
# create array x
import numpy as np
x = np.random.randint(0,10,20)
x

array([7, 5, 5, 5, 2, 4, 0, 7, 1, 1, 5, 8, 0, 0, 7, 8, 4, 9, 1, 5])

In [2]:
# print the shape of x
x.shape

(20,)

In [3]:
# create a two dimensional array
xy = np.array([np.random.randint(0,10,20), np.random.randint(0,10,20)])
xy

array([[2, 8, 0, 5, 7, 7, 2, 4, 8, 3, 7, 5, 2, 1, 9, 0, 9, 2, 9, 8],
       [8, 8, 0, 9, 4, 7, 3, 0, 2, 9, 7, 1, 4, 5, 3, 3, 3, 0, 8, 6]])

In [4]:
# print shape of 2d array
xy.shape

(2, 20)

In [12]:
# reshape the array to 2 x 6
np.reshape(xy, (2,20))

array([[2, 8, 0, 5, 7, 7, 2, 4, 8, 3, 7, 5, 2, 1, 9, 0, 9, 2, 9, 8],
       [8, 8, 0, 9, 4, 7, 3, 0, 2, 9, 7, 1, 4, 5, 3, 3, 3, 0, 8, 6]])

In [13]:
# reshape the array to 1 x 12
np.reshape(xy, (1,40))

array([[2, 8, 0, 5, 7, 7, 2, 4, 8, 3, 7, 5, 2, 1, 9, 0, 9, 2, 9, 8, 8, 8,
        0, 9, 4, 7, 3, 0, 2, 9, 7, 1, 4, 5, 3, 3, 3, 0, 8, 6]])

In [14]:
# transpose the array
np.transpose(xy)

array([[2, 8],
       [8, 8],
       [0, 0],
       [5, 9],
       [7, 4],
       [7, 7],
       [2, 3],
       [4, 0],
       [8, 2],
       [3, 9],
       [7, 7],
       [5, 1],
       [2, 4],
       [1, 5],
       [9, 3],
       [0, 3],
       [9, 3],
       [2, 0],
       [9, 8],
       [8, 6]])

In [15]:
# indexing method 1
x[4]

2

In [16]:
# indexing method 2
x[-2]

1

In [17]:
# indexing method 3
x[1:5]

array([5, 5, 5, 2])

In [32]:
# indexing method 4
indexing = np.array([2,5,14])
x[indexing]

array([5, 4, 7])

In [73]:
# indexing method 5
xy[0, xy[1]>3]

array([2, 8, 5, 7, 7, 3, 7, 2, 1, 9, 8])

In [74]:
x

array([7, 5, 5, 5, 2, 4, 0, 7, 1, 1, 5, 8, 0, 0, 7, 8, 4, 9, 1, 5])

In [84]:
# indexing method 6


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [51]:
x.any([x>3, x==1])

TypeError: an integer is required

In [54]:
xy[1, 1]

8

In [57]:
xy

TypeError: data type not understood

In [60]:
np.transpose(xy)

array([[2, 8],
       [8, 8],
       [0, 0],
       [5, 9],
       [7, 4],
       [7, 7],
       [2, 3],
       [4, 0],
       [8, 2],
       [3, 9],
       [7, 7],
       [5, 1],
       [2, 4],
       [1, 5],
       [9, 3],
       [0, 3],
       [9, 3],
       [2, 0],
       [9, 8],
       [8, 6]])

In [86]:
def variance(array):
    mean = np.mean(array)
    variances = (array - mean)**2
    return round(sum(variances)/len(variances), 2)
variance(x)

8.36

In [88]:
def stdev(array):
    return round(variance(array)**.5, 2)
stdev(x)

2.89