In [15]:
import numpy as np
array1 = np.arange(0, 10, 2)
array2 = np.arange(10,20,2)

In [16]:
array1

array([0, 2, 4, 6, 8])

In [17]:
array2

array([10, 12, 14, 16, 18])

In [18]:
array1 + array2

array([10, 14, 18, 22, 26])

In [19]:
array1 - array2

array([-10, -10, -10, -10, -10])

In [21]:
array1 * array2

array([  0,  24,  56,  96, 144])

In [27]:
np.dot(array1, array2)

320